require('dotenv').config()

const PORT = process.env.PORT;
const MONGODB_URI = process.env.MONGODB_URI;

const ADMIN_LOGIN_PASSWORD=process.env.ADMIN_LOGIN_PASSWORD;
const ADMIN_LOGIN_NAME=process.env.ADMIN_LOGIN_NAME;

const SECRET_KEY =process.env.SECRET_KEY;
const REFRESH_TOKEN_SECRET =process.env.REFRESH_TOKEN_SECRET;

const AWS_ACCESS_KEY=  process.env.AWS_ACCESS_KEY
const AWS_SECRET_KEY=process.env.AWS_SECRET_KEY
const AWS_REGION=process.env.AWS_REGION
const AWS_BUCKET_NAME=process.env.AWS_BUCKET_NAME 

const FACEBOOK_APP_ID = process.env.FACEBOOK_APP_ID;
const FACEBOOK_APP_SECRET = process.env.FACEBOOK_APP_SECRET;
const FACEBOOK_PAGE_ACCESS_TOKEN = process.env.FACEBOOK_PAGE_ACCESS_TOKEN;
const FACEBOOK_PAGE_ID = process.env.FACEBOOK_PAGE_ID;
const ADMIN_USER_ID = process.env.ADMIN_USER_ID;

const SOCKET_URL = process.env.SOCKET_URL;
module.exports = { 
   PORT, 
   MONGODB_URI,
   ADMIN_LOGIN_PASSWORD,
   ADMIN_LOGIN_NAME,
   SECRET_KEY,
   REFRESH_TOKEN_SECRET,
   AWS_BUCKET_NAME,
   AWS_ACCESS_KEY, 
   AWS_SECRET_KEY, 
   AWS_REGION,
   FACEBOOK_APP_ID,
   FACEBOOK_APP_SECRET,
   FACEBOOK_PAGE_ACCESS_TOKEN,
   FACEBOOK_PAGE_ID,
   SOCKET_URL,
   ADMIN_USER_ID
   }